# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: mixed-line-ending
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.267
    hooks:
      - id: ruff
        args: [--fix, --show-fixes, --exit-non-zero-on-fix]
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--filter-files]
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.0.1
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --remove-unused-variables
          - --ignore-init-module-imports
  - repo: https://github.com/dannysepler/rm_unneeded_f_str
    rev: v0.2.0
    hooks:
      - id: rm-unneeded-f-str
  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports
        exclude: .*/__init__.py
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0 # See: https://github.com/pre-commit/mirrors-prettier/tags
    hooks:
      - id: prettier
        types: [yaml]
